# ---- Project coordinates ----
group=com.hjm
version=0.1.0
# ---- Versions ----
kotlinVersion=2.0.20
springBootVersion=3.3.3
springDependencyManagementVersion=1.1.6
awsSdkVersion=2.25.54
jacksonVersion=2.17.2
okHttpVersion=4.12.0
jvmTarget=21
# ---- Gradle performance ----
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.configuration-cache=true
# ---- Kotlin ----
kotlin.incremental=true
kotlin.code.style=official
